
spring:
  application:
    name: archivarius
  datasource:
    driver-class-name: org.postgresql.Driver
    password: OLMOGREAT
    url: jdbc:postgresql://localhost:5432/dbforhost
    username: archi